Practical-10/Practical-10_1/Practical-10_1/Controllers/userController.cs
using Practical_10_1.Data.Model;
using Practical_10_1.Data.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practical_10_1.Controllers
{
    public class userController : Controller
    {
        //this interface defined in different project as Class library
        private readonly IUserData db;
        /// <summary>
        /// use dependency injection
        /// for parameterized constructor to pass interface as parameter
        /// Register ContainerConfig in Global.assx
        /// </summary>
        /// <param name="db"></param>
        public userController(IUserData db)
        {
            //initialized IuserData object 
            this.db = db;
        }

        // GET: user
        //to get all data 
        public ActionResult Index()
        {
            //call ViewAll method by context
            var model = db.ViewAll();
            return View(model);
        }

        //create a view
        //by default get method execute
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //when user submit this form than post method execute
        public ActionResult Create(User user)
        {
            //check if model is valid or not else empty or not
            if (ModelState.IsValid)
            {
                //call context as a create method and pass user model
                db.create(user);
                TempData["Message"] = "You have saved the user data!";
                return RedirectToAction("Details", new { id = user.Id });
            }
            return View();
        }
        //display user details
        public ActionResult Details(int id)
        {
            //find by user id
            var model = db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        /// <summary>
        /// by default called this method by clicking on edit link
        /// and display as per users data
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var modeel = db.Get(id);
            if (modeel == null)
            {
                return HttpNotFound();
            }
            return View(modeel);
        }

        /// <summary>
        /// when user submit form post method called and changes invoked
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                db.update(user);
                TempData["Message"] = "You have update the Data!";
                return RedirectToAction("Details", new { id = user.Id});
            }
            return View(user);
        }

        /// <summary>
        /// get method invoked and ask user are you conform
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        //user confirm to delete than delete method invoked
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection form)
        {
            db.Delete(id);
            TempData["Message"] = "You have Deleted the user ID="+id;
            return RedirectToAction("Index");
        }
    }
}

Practical-10/Practical-10_1/Practical-10_1/Views/user/Create.cshtml
@model Practical_10_1.Data.Model.User

@{
    ViewBag.Title = "Create";
}

<h2>Add User Data</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Of_Brith, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Of_Brith, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Of_Brith, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

Practical-10/Practical-10_1/Practical-10_1/Views/user/Delete.cshtml
@model Practical_10_1.Data.Model.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Brith)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Brith)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Practical-10/Practical-10_1/Practical-10_1/Views/user/Details.cshtml
@model Practical_10_1.Data.Model.User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Brith)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Brith)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Practical-10/Practical-10_1/Practical-10_1/Views/user/Edit.cshtml
@model Practical_10_1.Data.Model.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Of_Brith, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Of_Brith, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Of_Brith, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

Practical-10/Practical-10_1/Practical-10_1/Views/user/Index.cshtml
@model IEnumerable<Practical_10_1.Data.Model.User>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Add Data", "Create", "user", new { area = "" }, new { @class = "btn btn-primary" })
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date_Of_Brith)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>

Practical-10/Practical-10_1/Practical-10_1/Views/user/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
}

<h2>NotFound</h2>
<div> The User is not Found</div>
@Html.ActionLink("Back to List", "Index")